// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Use environment variables for flexible configuration
// In Vercel, these will be replaced at build time if set as environment variables
const SUPABASE_URL = "https://ynhgxwnkpbpzwbtzrzka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0";

// Debug logging (only in development)
if (typeof window !== 'undefined') {
  console.log('🔗 Supabase Client Configuration:');
  console.log('Connecting to URL:', SUPABASE_URL);
  console.log('Using key prefix:', SUPABASE_PUBLISHABLE_KEY.substring(0, 20) + '...');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Service role client for storage operations (bypasses RLS)
// This uses the service role key for operations that need elevated permissions
export const supabaseServiceRole = createClient(
  "https://ynhgxwnkpbpzwbtzrzka.supabase.co",
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluaGd4d25rcGJwendidHpyemthIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTc4NjE1OSwiZXhwIjoyMDcxMzYyMTU5fQ.4hohg8ZybIOX_frV6EHm2LwTRPYi07xEy6lRIkQZSUo",
  {
    auth: {
      autoRefreshToken: false,
      persistSession: false,
    },
    realtime: {
      params: {
        eventsPerSecond: 10,
      },
    },
    db: {
      schema: 'public',
    },
    global: {
      headers: {
        'X-Client-Info': 'factory-pulse-web-service-role',
      },
    },
    // Add timeout configuration for storage operations
    storage: {
      // Increase timeout for file uploads
      timeout: 60000, // 60 seconds
    },
  }
);

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
  db: {
    schema: 'public',
  },
  global: {
    headers: {
      'X-Client-Info': 'factory-pulse-web',
    },
  },
  // Add timeout configuration for storage operations
  storage: {
    // Increase timeout for file uploads
    timeout: 60000, // 60 seconds
  },
});